#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# v1.0 - initial release:
# Author: Davide Del Grande <davide.delgrande _ lanewan.it> / <delgrande.davide _ gmail.com>
# This plugin should support all APC InRow Gen2 - I tested ONLY on RD devices

# http://www.oidview.com/mibs/318/PowerNet-MIB.html
# Alarm Table has following structure:
# .1.3.6.1.4.1.318.1.1.13.4.3.1       -->  PowerNet-MIB::airIRRG2AlarmsTableSize.0 -> N
# .1.3.6.1.4.1.318.1.1.13.4.3.2.1.1   -->  PowerNet-MIB::airIRRG2AlarmsIndex.N
# .1.3.6.1.4.1.318.1.1.13.4.3.2.1.2   -->  PowerNet-MIB::airIRRG2AlarmsEventCode.N
# .1.3.6.1.4.1.318.1.1.13.4.3.2.1.3   -->  PowerNet-MIB::airIRRG2AlarmsDescription.N

# Output example with 2 alarms:
#.1.3.6.1.4.1.318.1.1.13.4.3.1.0 = INTEGER: 2
#.1.3.6.1.4.1.318.1.1.13.4.3.2.1.1.1 = INTEGER: 1
#.1.3.6.1.4.1.318.1.1.13.4.3.2.1.1.2 = INTEGER: 2
#.1.3.6.1.4.1.318.1.1.13.4.3.2.1.2.1 = INTEGER: 11282
#.1.3.6.1.4.1.318.1.1.13.4.3.2.1.2.2 = INTEGER: 11328
#.1.3.6.1.4.1.318.1.1.13.4.3.2.1.3.1 = STRING: "Rack Inlet High Temperature Violation"
#.1.3.6.1.4.1.318.1.1.13.4.3.2.1.3.2 = STRING: "Air Filter Run Hours Violation"

# import pprint; pprint.pprint(info)
#[[u'2', u''],
# [u'', u'Rack Inlet High Temperature Violation'],
# [u'', u'Air Filter Run Hours Violation']]


def inventory_apc_inrowg2_alarms(info):
    return [(None,None)]


def check_apc_inrowg2_alarms(_no_item, _no_params, info):
    alarmindex = saveint(info[0][0])
    if alarmindex == 0:
        yield 0, "No Alarms"
    else:
        for alarmdesc in info[1:]:
            yield 2, alarmdesc[1]



check_info["apc_inrowg2_alarms"] = {
    "inventory_function"      : inventory_apc_inrowg2_alarms,
    "check_function"          : check_apc_inrowg2_alarms,
    "service_description"     : "Alarms",
    "has_perfdata"            : False,
    "snmp_scan_function"      : lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.318.1.3.14.8"),
    "snmp_info"               : (".1.3.6.1.4.1.318.1.1.13.4.3", [ "1", "2.1.3" ] ), # airIRRG2AlarmsDescription
}

