#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def inventory_lenovostorcenter_disks(info):
    for name, status in info:
        params = {}
        yield name, params


def check_lenovostorcenter_disks(item, params, info):
    if params == None:
        params = {}

    for name, status in info:
        if name == item:
            if status == "NORMAL":
                message = u"Status: %s" % ( status )
                status_code = 0
            else:
                message = u"Status: %s (!!)" % ( status )
                status_code = 2

            return status_code, message


check_info["lenovostorcenter_disks"] = {
    "check_function"        : check_lenovostorcenter_disks,
    "inventory_function"    : inventory_lenovostorcenter_disks,
    "service_description"   : "%s",
    "has_perfdata"          : True,
    "snmp_scan_function"    : lenovostorcenter_scan_function,
    "snmp_info"             : (".1.3.6.1.4.1.11369.10.4.3.1", [
                                                      2, #Disk Name
                                                      4, #Disk Status
                                                   ]),
    "includes"              : [ "lenovostorcenter.include" ]
}
