#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def agent_rdspostgres_arguments(params, hostname, ipaddress):
    # User, Password
    return "%s %s %s" % ( quote_shell_string(ipaddress), quote_shell_string(params["username"]), quote_shell_string(params["password"]) )

special_agent_info['rdspostgres'] = agent_rdspostgres_arguments
